adding absolute paths for executeables

diff --git a/bin/start-sidekiq b/bin/start-sidekiq
--- a/bin/start-sidekiq
+++ b/bin/start-sidekiq
@@ -5,33 +5,30 @@ export RAILS_ENV=production
 export PATH="/opt/mastodon/bin:${PATH}"
 
     if [[ -n ${SIDEKIQ_THREADS} ]]; then
-        SIDEKIQ_THREADS=$(printf '%d' "${SIDEKIQ_THREADS}")
+        SIDEKIQ_THREADS=$(/usr/bin/printf '%d' "${SIDEKIQ_THREADS}")
     else
-        SIDEKIQ_THREADS=$(printf '%d' 5)
+        SIDEKIQ_THREADS=$(/usr/bin/printf '%d' 5)
     fi
 
-cd /opt/mastodon/bin || exit 1
+/usr/bin/cd /opt/mastodon/bin || exit 1
 
-bash show-sidekiq-branding;
+/bin/bash show-sidekiq-branding;
 
-bash start-sshd 
-bash start-nginx 
+/bin/bash start-sshd 
+/bin/bash start-nginx 
 
 if [[ ${SIDEKIQ_ONLY,,} == "true" ]] && [[ -n ${SIDEKIQ_QUEUE} ]]; then
-    echo "*** Starting sidekiq handling ${SIDEKIQ_QUEUE} queue with ${SIDEKIQ_THREADS} threads ***"
-    exec \
-        /opt/mastodon/bin/bundle exec "sidekiq -q ${SIDEKIQ_QUEUE} -c ${SIDEKIQ_THREADS}" 
+    /bin/echo "*** Starting sidekiq handling ${SIDEKIQ_QUEUE} queue with ${SIDEKIQ_THREADS} threads ***"
+    /opt/mastodon/bin/bundle exec "sidekiq -q ${SIDEKIQ_QUEUE} -c ${SIDEKIQ_THREADS}" 
 elif [[ ${SIDEKIQ_ONLY,,} == "true" ]] && [[ -z ${SIDEKIQ_QUEUE} ]]; then
-    echo "*** No sidekiq queue specified, aborting ***"
-    sleep infinity &
+    /bin/echo "*** No sidekiq queue specified, aborting ***"
+    /usr/bin/sleep infinity &
 elif [[ ${SIDEKIQ_DEFAULT,,} == "true" ]]; then
-    echo "*** Starting sidekiq handling default queue with ${SIDEKIQ_THREADS} threads ***"
-    exec \
-        /opt/mastodon/bin/bundle exec "sidekiq -q default -c ${SIDEKIQ_THREADS}" 
+    /bin/echo "*** Starting sidekiq handling default queue with ${SIDEKIQ_THREADS} threads ***"
+    /opt/mastodon/bin/bundle exec "sidekiq -q default -c ${SIDEKIQ_THREADS}" 
 else
-    echo "*** Starting sidekiq handling all queues with ${SIDEKIQ_THREADS} threads ***"
-    exec \
-        /opt/mastodon/bin/bundle exec "sidekiq -c ${SIDEKIQ_THREADS}" 
+    /bin/echo "*** Starting sidekiq handling all queues with ${SIDEKIQ_THREADS} threads ***"
+    /opt/mastodon/bin/bundle exec "sidekiq -c ${SIDEKIQ_THREADS}" 
 fi
 
     # if [[ ${SIDEKIQ_ONLY,,} != "true" ]]; then
